### ISSUE TITLE
Micro plugin failed

### ISSUE THREAD

**Issue by paletochen** [DreamMaoMao/fg.yazi#1]
Right after installing the plugin and adding the keymaps as instructed, I get the following error in the task manager when trying to use it:

```
Micro plugin failed:
runtime error: [string "/home/user/.cargo/registry/src/index.crates...."]:36: attempt to call a nil value (method 'wait_with_output')
stack traceback:
        [string "/home/user/.cargo/registry/src/index.crates...."]:36: in function <[string "/home/user/.cargo/registry/src/index.crates...."]:16>
```

```
yazi --debug
Yazi
    yazi 0.2.4 (VERGEN_IDEMPOTENT_OUTPUT 2024-03-10)

Environment
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

tmux
    TMUX: false

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-1")
    DISPLAY: Some(":0")

Ueberzug
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false
```

**Comment by sxyazi** [comment]
Hi, as the readme said this plugin requires the latest main branch of Yazi, `wait_with_output` is a new method added recently.

**Comment by paletochen** [comment]
> Hi, as the readme said this plugin requires the latest main branch of Yazi, `wait_with_output` is a new method added recently.

Oh, sorry for that then.
I always understood "main branch" as stable version so I thought that my yazi version would not be the problem

**Comment by paletochen** [comment]
I confirmed that after building `yazi` from source the plugin works.

Thanks for your help :)
